#!/bin/sh
# PUC-Rio
# INF1715 Compiladores
# Gabriel de Quadros Ligneul 1212560

if [ "$#" -lt 1 ]; then
    echo "error: must provide a file"
    exit 1
fi

if [ ! -r $1 ]; then
    echo "error: cannot read file '$1'"
    exit 1
fi

cpp -P -I lib/include -o "$1".1 "$1" && \
./bin/mc < "$1".1 > "$1".s && \
gcc -m32 -g -c -o "$1".o "$1".s && \
gcc -m32 -o "$1"._ "$1".o $( find lib/obj -name "*.o" ) && \
./"$1"._ > "$1".out && \
cat "$1".out

if [ "$2" != "-t" ]; then
    rm -f "$1".*
fi

