global: global1
function: empty --- 0
function: paramonly --- 0
param --- movl 8(%ebp), %eax
function: varonly --- subl $8, %ebp
a --- movl -4(%ebp), %eax
b --- movl -8(%ebp), %eax
function: foo --- subl $12, %ebp
p1 --- movl 8(%ebp), %eax
p2 --- movl 12(%ebp), %eax
p3 --- movl 16(%ebp), %eax
v1 --- movl -4(%ebp), %eax
v2 --- movl -8(%ebp), %eax
v3 --- movl -12(%ebp), %eax
global: global2
function: main --- subl $28, %ebp
a --- movl -4(%ebp), %eax
b --- movl -8(%ebp), %eax
c --- movl -12(%ebp), %eax
d --- movl -16(%ebp), %eax
e --- movl -20(%ebp), %eax
f --- movl -24(%ebp), %eax
g --- movl -24(%ebp), %eax
h --- movl -28(%ebp), %eax
i --- movl -16(%ebp), %eax
j --- movl -20(%ebp), %eax
