/*
 * Monga Language
 * Author: Gabriel de Quadros Ligneul
 *
 * parser.h
 * Parses the input using the scanner output.
 */

#ifndef PARSER_H
#define PARSER_H

#include "ast/ast.h"
#include "parser/parser.tab.h"

/* Yacc parser function prototype, returns 0 on success */
int yyparse();

/* AST generated by the parser */
extern AstDeclaration* parser_ast;

#endif

