/*
 * PUC-Rio
 * INF1715 Compiladores
 * Gabriel de Quadros Ligneul 1212560
 *
 * parser.h
 * Parses the input using the scanner output.
 */

#ifndef PARSER_H
#define PARSER_H

#include "ast/ast.h"
#include "parser/parser.tab.h"

/* Yacc parser function prototype
 * Returns 0 on success */
int yyparse();

/* AST generated by the parser */
extern ast_decl_t* parser_ast;

#endif

