
(func int main<7>
  (block
    (var bool a<8>)
    (assign a<8> (> 1.000000:float (int->float 1:int):float):bool)
    (assign a<8> (>= 2.000000:float (int->float 2:int):float):bool)
    (assign a<8> (< 3.000000:float (int->float 3:int):float):bool)
    (assign a<8> (<= 4.000000:float (int->float 4:int):float):bool)
    (assign a<8> (> 1.000000:float 1.000000:float):bool)
    (assign a<8> (>= 2.000000:float 2.000000:float):bool)
    (assign a<8> (< 3.000000:float 3.000000:float):bool)
    (assign a<8> (<= 4.000000:float 4.100000:float):bool)
    (return 0:int)))
