
(func int main<7>
  (block
    (var int a<8>)
    (assign a<8> (float->int (+ 1.000000:float (int->float 1:int):float):float):int)
    (assign a<8> (float->int (- 1.000000:float (int->float 1:int):float):float):int)
    (assign a<8> (float->int (* 1.000000:float (int->float 1:int):float):float):int)
    (assign a<8> (float->int (/ 1.000000:float (int->float 1:int):float):float):int)
    (return 0:int)))
