
(func void foo1<6>
  (block
    (return)))

(func void foo2<10>
  (var bool cond<10>)
  (block
    (var int a<11>)
    (assign a<11> 5:int)
    (if cond<10>:bool
        (return))
    (return)))

(func void foo3<18>
  (var bool cond<18>)
  (block
    (var int a<19>)
    (assign a<19> 5:int)
    (if cond<18>:bool
        (return)
        (return))))

(func void foo4<27>
  (var bool cond1<27>)
  (var bool cond2<27>)
  (block
    (var int a<28>)
    (var int b<28>)
    (if cond1<27>:bool
        (block
          (if cond2<27>:bool
              (block
                (return))
              (block
                (assign a<28> 10:int)
                (return))))
        (block
          (return)))))

(func void foo5<41>
  (block
    (while true:bool
      (return))
    (return)))

(func void foo6<47>
  (var bool cond<47>)
  (block
    (while true:bool
      (if cond<47>:bool
          (return)))
    (return)))
