
(func char[] foo<9>
  (var int x<9>)
  (block
    (return (new char[x]))))

(func float bar<13>
  (var int y<13>)
  (var int z<13>)
  (block
    (return (+ y z))))

(func int boo<17>
  (var char w<17>)
  (block
    (return w)))

(func int main<21>
  (block
    (var int a<22>)
    (var int b<22>)
    (var int c<22>)
    (var int d<22>)
    (var int e<22>)
    (var char[] s<23>)
    (assign s (foo (bar a (boo b))))
    (assign s (new char[(bar a b)]))
    (assign s[(foo (bar a b))] c)
    (assign a (+ (foo (boo b))[c] d))
    (assign a (* (- (foo (boo b))[(+ c d)]) e))
    (return 0)))
