
(proto char[] foo<9>
  (var int x<9>))

(proto float bar<10>
  (var int y<10>)
  (var int z<10>))

(proto int boo<11>
  (var char w<11>))

(func int main<13>
  (block
    (var int a<14>)
    (var int b<14>)
    (var int c<14>)
    (var int d<14>)
    (var int e<14>)
    (var char[] s<15>)
    (assign s (foo (bar a (boo b))))
    (assign s (new char[(bar a b)]))
    (assign s[(foo (bar a b))] c)
    (assign a (+ (foo (boo b))[c] d))
    (assign a (* (- (foo (boo b))[(+ c d)]) e))
    (return 0)))
