
(func float[][] get_matrix<9>
  (block
    (return null)))

(func int main<13>
  (block
    (var char c<14>)
    (var int i<15>)
    (var float f<16>)
    (var char[] s<17>)
    (assign c 258)
    (assign i c)
    (assign f i)
    (assign f 10.200000)
    (assign f (get_matrix)[1][1])
    (assign s "hello world")
    (assign c s[1])
    (assign i "string"[3])
    (assign i 2748)
    (return 0)))
